name: 🛫 CI
on: 
  workflow_call:
jobs:
  api-platform-ci:
    name: API-Platform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: php-pdo, php-pgsql, php-sodium, php-zip, unzip, php-intl
          coverage: none
          tools: composer:v2.5.2
        env:
          update: true
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader
      - name: Create env file and dump env vars to .env (prod)
        run: echo "${{ secrets.ENV_FILE }}" > .env && composer dump-env prod
      - name: Install bundle's web assets under a public directory
        run: php bin/console assets:install --symlink --relative public
      - name: Upload API-Platform artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-platform
          path: "./api"
          retention-days: 1
  app-ci:
    name: Vue App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build frontend
        run: npm run build
        env:
          NODE_ENV: production
          VITE_BASE_API_URL: https://challenge.rklf.fr/api
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./app/dist
          retention-days: 1
