name: 🚀 Deployment
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: 🛫 CI
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  deploy:
    name: 🚀 Deployment
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: api-platform
          path: "./api"
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: app
          path: "./app"
      - name: Deploy to SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ''
          rm: true
          source: .
          target: ${{ secrets.SSH_TARGET }}
      - name: Clear cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ''
          script: |
            cd ${{ secrets.SSH_TARGET }}/api
            php bin/console cache:clear --env=prod
